# Generated by Django 5.2.17 on 2026-08-14 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_from', models.CharField(blank=True, default='', max_length=64, verbose_name='criado de (IP)')),
                ('updated_from', models.CharField(blank=True, default='', max_length=64, verbose_name='atualizado de (IP)')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('scope_seed', models.TextField(help_text='Indexado como âncora de domínio (substitui DOMAIN_SEED_ANCHORS).', verbose_name='texto-semente de escopo')),
                ('contact_channel', models.CharField(help_text='Ex.: GLPI, Atendimento ao Colaborador.', max_length=120, verbose_name='canal de contato')),
                ('contact_hint', models.CharField(blank=True, default='', max_length=255, verbose_name='dica do canal')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'domínio',
                'verbose_name_plural': 'domínios',
                'db_table': 'kb_domain',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_from', models.CharField(blank=True, default='', max_length=64, verbose_name='criado de (IP)')),
                ('updated_from', models.CharField(blank=True, default='', max_length=64, verbose_name='atualizado de (IP)')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('classification', models.CharField(choices=[('Publica', 'Pública'), ('Interno', 'Interno'), ('Restrita', 'Restrita'), ('Confidencial', 'Confidencial')], default='Interno', max_length=32, verbose_name='classificação')),
                ('sensitive', models.BooleanField(default=False, verbose_name='sensível')),
                ('owner', models.CharField(blank=True, default='', max_length=120, verbose_name='responsável')),
                ('body', models.TextField(verbose_name='corpo (Markdown)')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='hash do conteúdo')),
                ('is_published', models.BooleanField(default=False, help_text='Só publicados (+ gate Interno/sensitive) entram no índice.', verbose_name='publicado')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='kb.domain', verbose_name='domínio')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'db_table': 'kb_document',
                'ordering': ('title',),
                'indexes': [models.Index(fields=['is_published', 'classification', 'sensitive'], name='kb_document_is_publ_b58271_idx'), models.Index(fields=['domain', 'is_published'], name='kb_document_domain__d0a83e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_from', models.CharField(blank=True, default='', max_length=64, verbose_name='criado de (IP)')),
                ('updated_from', models.CharField(blank=True, default='', max_length=64, verbose_name='atualizado de (IP)')),
                ('can_add', models.BooleanField(default=True, verbose_name='pode criar')),
                ('can_change', models.BooleanField(default=True, verbose_name='pode editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='pode excluir')),
                ('can_publish', models.BooleanField(default=False, help_text='Publicar e alterar classification/sensitive que afetam o índice.', verbose_name='pode publicar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='kb.domain', verbose_name='domínio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'vínculo usuário–domínio',
                'verbose_name_plural': 'vínculos usuário–domínio',
                'db_table': 'kb_domain_membership',
                'constraints': [models.UniqueConstraint(fields=('user', 'domain'), name='kb_membership_user_domain_uniq')],
            },
        ),
    ]
